#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
//#include "images/background.h"
#include "images/background.h"
#include "images/garbage.h"
#include "images/cockroach.h"
#include "images/start.h"
#include "images/bckcut.h"
#include "images/picha.h"
#include "images/win.h"



/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  BACKGROUND,
  WIN,
  //LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  //static char str[3];

  struct platform plat = {80, 70, 1, 20, 20};
  struct picha agent = {130, 0, 4, 20, 20, 0, 30, 2, 10};
  struct block blck = {130, 30, 5, 5};
  agent.row = agent.row - agent.height;
  int prev = agent.row;
  int prevheight = agent.height;
  struct bullet bullet1 = {126, 240, 5, 1};
  d1.c[0] = 'D';
  d1.c[1] = 'E';
  d1.c[2] = 'A';
  d1.c[3] = 'T';
  d1.c[4] = 'H';
  d1.c[5] = ':';
  d1.c[6] = ' ';
  d1.c[7] = ' ';
  d1.c[8] = ' ';
  d1.c[9] = 48;




  //int buttonWasDown[NBUTTONS] = {0};
  //int buttonJustReleased[NBUTTONS] = {0};

  // Load initial application state
  enum gba_state state = START;
  //struct state cs, ps;
  //cs.gba_state = START;

  while (1) {
    waitForVBlank();

    previousButtons = currentButtons;
    currentButtons = BUTTONS; // Load the current state of the buttons
    //previousButtons = KEY_DOWN(currentButtons);

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    //UNUSED(previousButtons);
    switch (state) {
      case START:
        //setPixel(10, 10, BLUE);
        //drawRectDMA(0, 0, 10, 10, BLUE);
        //drawImageDMA(0, 0, 240, 320, start);
        d1.c[0] = 'D';
        d1.c[1] = 'E';
        d1.c[2] = 'A';
        d1.c[3] = 'T';
        d1.c[4] = 'H';
        d1.c[5] = ':';
        d1.c[6] = ' ';
        d1.c[7] = ' ';
        d1.c[8] = ' ';
        d1.c[9] = 48;
        agent.deaths = 0;
        agent.col = 0;
        drawFullScreenImageDMA(start);
        waitForVBlank();
        drawString(10, 10, d1.c, WHITE);
        agent.height = prevheight;
        agent.row = prev;

        //drawString(10, 80, str, WHITE);

        //drawString(80, 120, "START", BLUE);
        if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons) || KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = BACKGROUND;
        }
        // state = ?
        break;
      case BACKGROUND:
        //drawImageDMA(0, 0, 80, 80, background);
      
        drawFullScreenImageDMA(background);
        waitForVBlank();
        drawRectDMA(130, 0, 240, 5, RED);
        waitForVBlank();
        drawRectDMA(plat.row, plat.col, plat.width, plat.height, GREEN);
                //drawImageDMA(80, 0, 50, 37, cockroach);
        plat.col += plat.disp;

        state = PLAY;
        break;
      case PLAY:
      
        //drawImageDMA(0, plat.col, 1, 1, (background + OFFSET(plat.row, plat.col, 1)));
        if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        
        //drawImageDMA(0, 0, 240, 160, background + OFFSET(plat.row, plat.col + plat.height, 20));
        drawFullScreenImageDMA(background);
        //waitForVBlank();
        UNUSED(blck);
        drawImageDMA(agent.row, agent.col, agent.width, agent.height, picha);
        //drawString(10, 20, str, WHITE);
        drawRectDMA(plat.row, plat.col, plat.width, plat.height, GREEN);
        //drawRectDMA(blck.row, blck.col, blck.width, blck.height, BLACK);
        drawRectDMA(bullet1.row, bullet1.col, bullet1.size, bullet1.size, WHITE);
        drawRectDMA(130, 0, 240, 5, RED);
        //waitForVBlank();
        drawString(140, 0, d1.c, WHITE);
        if(agent.row < prev) {
          agent.row += agent.gravity;
        }


        if(agent.col + agent.width >= 240) {
          state = WIN;
        }
        if((plat.row == 80)) {
          plat.disp = 1;
        } else if((plat.row + plat.height == 130)) {
          plat.disp = -1;
        }
        //if agent dies
        if(((agent.col + agent.width >= bullet1.col) && (agent.col <= bullet1.col) && (agent.row + agent.height >= bullet1.row))) {
        	bullet1.col = 240;
       	  agent.col = 10;
          agent.deaths++;
          int pp = agent.deaths;
          int i = 9;
          while(pp != 0 && i >= 7) {
            d1.c[i] = (pp%10) + 48;
            pp /= 10;
            i--;
          }
        }
        if((agent.col + agent.width > plat.col && agent.col < plat.col + plat.width && plat.row >= prev - agent.height)) {
          agent.col = 10;
          agent.deaths++;
          int pp = agent.deaths;
          int i = 9;
          while(pp != 0 && i >= 7) {
            d1.c[i] = (pp%10) + 48;
            pp /= 10;
            i--;
          }
        } else if((plat.row <= agent.row - agent.height || agent.col + agent.width + agent.disp <= plat.col || agent.col - agent.disp >= plat.col + plat.width)) {
          if(KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons) && agent.col - agent.disp >= 0) {
            agent.col -= agent.disp;
          } else if(KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
            agent.col += agent.disp;
          }
        }

        //up down
        if(agent.height != prevheight && KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          agent.height = prevheight;
          agent.row = prev;
        } else {
          if(KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons) && agent.row == prev) {
            agent.row -= agent.jump;
          }
          if(KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons) && agent.row == prev) {
            agent.row += agent.crouch;
            agent.height -= agent.crouch;
          }
        }
        plat.row += plat.disp;
        if(bullet1.col < 0) {
        	bullet1.col = 240;
        }
        bullet1.col -= bullet1.speed;

        
        break;
      case WIN:
              if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        drawFullScreenImageDMA(win);
        break;
    }

    //previousButtons = currentButtons; // Store the current state of the buttons
  }

  //UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
